name: deploy
on:
  push:
  workflow_dispatch:

jobs:
  generate-algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: caibingcheng/hugo-algolia2@v1
        with:
          input: "./posts/**"
          output: "./algolia.json"
          index: ${{ secrets.ALGOLIA_INDEX_NAME }}
          apikey: ${{ secrets.ALGOLIA_API_KEY }}
          appid: ${{ secrets.ALGOLIA_APP_ID }}
