name: deploy
on:
  push:
  workflow_dispatch:

jobs:
  generate-algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: iChochy/Algolia-Upload-Records@main
        env:
         APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
         ADMIN_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
         INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
         FILE_PATH: "./algolia.json"
